
spring:
  application:
    name: dong

  messages:
    encoding: UTF-8

  profiles:
    include: auth
    active: dev
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 10
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true


logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace